name: CraftSprint.io Build (WebGL)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Defold WebGL
        uses: defold/doc@v1
        # Ya direct official bob action:
        with:
          args: --archive --platform js-web resolve build bundle --bundle-output build/web

      - name: Upload WebGL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CraftSprint-WebGL
          path: build/web/
